moddelmsg:
  max_hours: 24
  default_hours: 12
  default_timeout_hours: 24
  timeout_remove_roleid: 123123123123
  notify_channelid: 456456456456
  notify_user_id: 789789789789
  quarantine_roleid: 123456789
  quarantine_channelid: 123456789
  quarantine_writepermission_roleid: 123456789
  forbidden_regexes:
    - "badword1"
    - "badword2"
    - "badword3"
